import { useState } from "react";
import { Header, Icon, useLocalConfig } from "../shared.jsx";

function buildComponent({ spaceId, cdaToken, environment }) {
  const env = environment || "master";
  return `// components/OmniTrackInjector.tsx
// Auto-generated by OmniTrack. Drop into your Next.js app.
// Renders GA4/GTM/GSC head snippets + JSON-LD schemas from Contentful.

import Script from "next/script";

const SPACE_ID = process.env.CONTENTFUL_SPACE_ID || "${spaceId}";
const CDA_TOKEN = process.env.CONTENTFUL_CDA_TOKEN || "${cdaToken}";
const ENV = process.env.CONTENTFUL_ENV || "${env}";
const API = \`https://cdn.contentful.com/spaces/\${SPACE_ID}/environments/\${ENV}\`;

async function cf(path: string) {
  const res = await fetch(\`\${API}\${path}&access_token=\${CDA_TOKEN}\`, { next: { revalidate: 300 } });
  if (!res.ok) return { items: [] };
  return res.json();
}

export async function getOmniTrackHead() {
  const [heads, schemas] = await Promise.all([
    cf("/entries?content_type=headSnippet&limit=100"),
    cf("/entries?content_type=seoSchema&limit=200"),
  ]);
  return { heads: heads.items || [], schemas: schemas.items || [] };
}

// --- Server Component (Next.js App Router) ---
// Place inside <head> in app/layout.tsx:
//   import { OmniTrackHead } from "@/components/OmniTrackInjector";
//   <head><OmniTrackHead slug={params.slug} /></head>

export async function OmniTrackHead({ slug }: { slug?: string }) {
  const { heads, schemas } = await getOmniTrackHead();
  const headTags = heads.filter((e: any) =>
    ["ga4", "gtm-head", "gsc"].includes(e.fields?.toolType)
  );
  const matchedSchemas = slug
    ? schemas.filter((s: any) => {
        const src = s.fields?.sourceEntryId;
        return src && slug.includes(src);
      })
    : schemas;

  return (
    <>
      {headTags.map((e: any) => (
        <div
          key={e.sys.id}
          dangerouslySetInnerHTML={{ __html: e.fields.code }}
        />
      ))}
      {matchedSchemas.map((s: any) => (
        <script
          key={s.sys.id}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: s.fields.jsonLd }}
        />
      ))}
    </>
  );
}

// --- Body noscript (GTM) ---
// Place as the first child inside <body> in app/layout.tsx:
//   <body><OmniTrackBody />{children}</body>

export async function OmniTrackBody() {
  const { heads } = await getOmniTrackHead();
  const body = heads.filter((e: any) => e.fields?.toolType === "gtm-body");
  return (
    <>
      {body.map((e: any) => (
        <div
          key={e.sys.id}
          dangerouslySetInnerHTML={{ __html: e.fields.code }}
        />
      ))}
    </>
  );
}
`;
}

const LAYOUT_SNIPPET = `// app/layout.tsx
import { OmniTrackHead, OmniTrackBody } from "@/components/OmniTrackInjector";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* @ts-expect-error Async Server Component */}
        <OmniTrackHead />
      </head>
      <body>
        {/* @ts-expect-error Async Server Component */}
        <OmniTrackBody />
        {children}
      </body>
    </html>
  );
}`;

const ENV_SNIPPET = `# .env.local
CONTENTFUL_SPACE_ID=YOUR_SPACE_ID
CONTENTFUL_CDA_TOKEN=YOUR_CDA_TOKEN
CONTENTFUL_ENV=master`;

export default function NextJsIntegrationTool({ onHome }) {
  const [config, setConfig] = useLocalConfig("omnitrack:nextjs", {
    spaceId: "", cdaToken: "", environment: "master"
  });
  const [copied, setCopied] = useState(null);

  const component = buildComponent(config);

  function copy(which, text) {
    navigator.clipboard.writeText(text);
    setCopied(which);
    setTimeout(() => setCopied(null), 1500);
  }

  function downloadFile(name, contents) {
    const blob = new Blob([contents], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="app">
      <Header title="Next.js Integration" subtitle="One-file drop-in that renders GA4/GTM/GSC/Schema from Contentful" onHome={onHome} />
      <p className="phase-title">Generate Your Next.js Component</p>
      <p className="phase-sub">
        Fill in your Contentful credentials below, download <code>OmniTrackInjector.tsx</code>,
        drop it into <code>components/</code> in your Next.js app, then add the 3-line layout integration.
        App-Router compatible (Next.js 13+).
      </p>

      <div className="card">
        <div className="card-title"><span className="dot" />Runtime Contentful Credentials (read-only CDA)</div>
        <div className="field-row">
          <div>
            <label>SPACE ID</label>
            <input type="text" placeholder="xz1a2b3c4d5e"
              value={config.spaceId}
              onChange={e => setConfig(p => ({ ...p, spaceId: e.target.value }))} />
          </div>
          <div>
            <label>CDA TOKEN</label>
            <input type="password" placeholder="Content Delivery API token"
              value={config.cdaToken}
              onChange={e => setConfig(p => ({ ...p, cdaToken: e.target.value }))} />
          </div>
        </div>
        <label>ENVIRONMENT</label>
        <input type="text" placeholder="master"
          value={config.environment}
          onChange={e => setConfig(p => ({ ...p, environment: e.target.value }))} />
      </div>

      <div className="card">
        <div className="card-title">
          <span className="dot" />Step 1 {"\u00B7"} components/OmniTrackInjector.tsx
          <span style={{ marginLeft: "auto", display: "flex", gap: 6 }}>
            <button className="copy-btn" onClick={() => copy("comp", component)}>
              {copied === "comp" ? "\u2713 Copied" : "\u29C7 Copy"}
            </button>
            <button className="copy-btn" onClick={() => downloadFile("OmniTrackInjector.tsx", component)}>
              <Icon name="download" /> Download
            </button>
          </span>
        </div>
        <div className="script-block">
          <div className="script-header">
            <div className="script-label"><strong>OmniTrackInjector.tsx</strong> {"\u00B7"} Server Component</div>
          </div>
          <pre>{component}</pre>
        </div>
      </div>

      <div className="card">
        <div className="card-title">
          <span className="dot" />Step 2 {"\u00B7"} app/layout.tsx
          <button className="copy-btn" style={{ marginLeft: "auto" }} onClick={() => copy("layout", LAYOUT_SNIPPET)}>
            {copied === "layout" ? "\u2713 Copied" : "\u29C7 Copy"}
          </button>
        </div>
        <div className="script-block">
          <pre>{LAYOUT_SNIPPET}</pre>
        </div>
      </div>

      <div className="card">
        <div className="card-title">
          <span className="dot" />Step 3 {"\u00B7"} .env.local (optional \u2014 credentials baked in by default)
          <button className="copy-btn" style={{ marginLeft: "auto" }} onClick={() => copy("env", ENV_SNIPPET)}>
            {copied === "env" ? "\u2713 Copied" : "\u29C7 Copy"}
          </button>
        </div>
        <div className="script-block">
          <pre>{ENV_SNIPPET}</pre>
        </div>
      </div>

      <div className="status-row info">
        <Icon name="check" /> After deploying Next.js once with this component, every future injection from OmniTrack appears on your live site within 5 min (ISR revalidate=300).
      </div>

      <div className="actions">
        <button className="btn btn-ghost" onClick={onHome}><Icon name="back" /> Home</button>
        <div className="spacer" />
        <button className="btn btn-primary" onClick={() => downloadFile("OmniTrackInjector.tsx", component)}>
          <Icon name="download" /> Download Component
        </button>
      </div>
    </div>
  );
}
